module.exports = {
  calendar: require("./calendar.png"),
  mobileIcon: require("./mobileIcon.svg"),
  locationPin: require("./locationPing.svg"),
  envelope: require("./envelope.png"),
  githubLogo: require("./githubLogo.png"),
  stackoverflowLogo: require("./stackoverflowLogo.png"),
  stackoverflowBlack: require("./stackoverflowBlack.png"),
  stackoverflowWhite: require("./stackoverflowWhite.png"),
  githubBlack: require("./githubBlack.png"),
  githubWhite: require("./githubWhite.png"),
  mainBackground: require("./mainBackground.jpg"),
  author: require("./author.JPG"),
  linkedinWhite: require("./linkedinWhite.png"),
  linkedinBlack: require("./linkedinBlack.png"),
  techsophyLogo: require("./techsophyLogo.jpg"),
  abhipaisaLogo: require("./abhipaisa-logo.png"),
  fanduniyaLogo: require("./fanduniya-logo.png"),
  tahakomLogo: require("./tahkom.png"),
  bmsLogo: require("./visionplanner.png"),
  carretDown: require("./carretDown.svg"),
  carretUp: require("./carretUp.svg")
};
